challenges:
  - name: "Challenge 1"
    description: ""
    flag: "this_is_wrong"
    points: 50
    hint: "Did you wait enough ?"
  - name: "Challenge 2"
    description: ""
    flag: "this_is_not_secret"
    points: 50
    hint: "Is the config right ?"
  - name: "Challenge 3"
    description: ""
    flag: "this_is_a_funky_beast"
    points: 100
    hint: "These things are secret"
  - name: "Challenge 4"
    description: ""
    flag: "you_caught_me"
    points: 250
    hint: "Base64 encoding might be involved"