challenges:
  - name: "Challenge 1"
    description: "Find the flag in ctf-ch1 namespace"
    flag: "this_is_wrong"
    points: 50
    hint: "Did you wait enough ?"
  - name: "Challenge 2"
    description: "Find the flag in ctf-ch2 namespace"
    flag: "this_is_not_secret"
    points: 50
    hint: "Is the config right ?"
  - name: "Challenge 3"
    description: "Find the flag in ctf-ch3 namespace"
    flag: "this_is_a_funky_beast"
    points: 100
    hint: "These things are secret"
  - name: "Challenge 4"
    description: "Find the flag in ctf-ch4 namespace"
    flag: "you_caught_me"
    points: 250
    hint: "Did you access the frontend?"
  - name: "Challenge 5"
    description: "Find the flag in ctf-ch5 namespace"
    flag: "you_caught_me"
    points: 250
    hint: "This one is well cached"

participants:
  - token: "CTF-AC3HR3"
    name: "Player01"
  - token: "CTF-GF92LV"
    name: "Player02"
  - token: "CTF-XSPH99"
    name: "Player03"
  - token: "CTF-RA26MV"
    name: "Player04"
  - token: "CTF-C2LUQ6"
    name: "Player05"
  - token: "CTF-L5VXS4"
    name: "Player06"
  - token: "CTF-LLCP9Q"
    name: "Player07"
  - token: "CTF-L1Y416"
    name: "Player08"
  - token: "CTF-S4LJAE"
    name: "Player09"
  - token: "CTF-VJK63J"
    name: "Player10"
  - token: "CTF-ZIHECI"
    name: "Player11"
  - token: "CTF-YQTQ95"
    name: "Player12"
  - token: "CTF-U27ZLJ"
    name: "Player13"
  - token: "CTF-HNOHK3"
    name: "Player14"
  - token: "CTF-YYM62A"
    name: "Player15"
  - token: "CTF-3OBP79"
    name: "Player16"
  - token: "CTF-ADH0VX"
    name: "Player17"
  - token: "CTF-NTEAGK"
    name: "Player18"
  - token: "CTF-3C6TCQ"
    name: "Player19"
  - token: "CTF-H4WW55"
    name: "Player20"
  - token: "CTF-O0K13B"
    name: "Player21"
  - token: "CTF-RU11WM"
    name: "Player22"
  - token: "CTF-HDSY3F"
    name: "Player23"
  - token: "CTF-WG4SOI"
    name: "Player24"
  - token: "CTF-TFXLU0"
    name: "Player25"
  - token: "CTF-HQTVIK"
    name: "Player26"
  - token: "CTF-J7ZNWN"
    name: "Player27"
  - token: "CTF-XPY1EM"
    name: "Player28"
  - token: "CTF-FINDLR"
    name: "Player29"
  - token: "CTF-9J35T7"
    name: "Player30"
  - token: "CTF-RA6O5Q"
    name: "Player31"
  - token: "CTF-SB3YTW"
    name: "Player32"
  - token: "CTF-OF6LML"
    name: "Player33"
  - token: "CTF-E3P01Z"
    name: "Player34"
  - token: "CTF-AGD49H"
    name: "Player35"

organizers:
  - token: "ADMIN-MAIN"
    name: "Main Administrator"
  - token: "ADMIN-ASST"
    name: "Assistant Administrator"